import type { TacticDocumentV1 } from "@basketball/shared";

/**
 * Built-ins are teaching-friendly snapshots of classic actions. Each template
 * includes realistic offensive spacing plus defensive coverage/rotation so the
 * motion trails show both sides of the read.
 */
export interface Template {
  id: string;
  version: number;
  nameKey: string;
  descKey: string;
  coaching: {
    phase: LocalizedText;
    level: "foundation" | "intermediate" | "advanced";
    format: string;
    coverage: LocalizedText;
    focus: LocalizedText[];
    reads: LocalizedText[];
    previewAtMs: number;
  };
  eventCopyZh?: Record<number, TemplateEventCopy>;
  document: TacticDocumentV1;
}

type LocalizedText = { zh: string; en: string };

type TemplateEventCopy = {
  note?: string;
  explanation?: string;
  readTrigger?: string;
  playerTask?: string;
  commonMistake?: string;
  optionLabels?: string[];
};

type PlayerActor = Extract<TacticDocumentV1["actors"][number], { type: "player" }>;
type BallActor = Extract<TacticDocumentV1["actors"][number], { type: "ball" }>;
type Keyframe = TacticDocumentV1["keyframes"][number];
type PoseMap = Keyframe["poses"];

const BASE_TEAMS = {
  offense: { id: "o", label: "Offense", color: "#c8332f" },
  defense: { id: "d", label: "Defense", color: "#2155a6" },
};

const HALF_COURT = {
  preset: "half",
  orientation: "home_attacks_right",
  sizeMeters: { length: 14, width: 15 },
};

const FULL_COURT = {
  preset: "full",
  orientation: "home_attacks_right",
  sizeMeters: { length: 28, width: 15 },
};

const COMMON_DOC = {
  interpolation: { position: "linear", facing: "shortestAngle" },
  rules: { coordinateSystem: "normalized" as const, bounds: { x: [0, 1] as [number, number], y: [0, 1] as [number, number] } },
};

/** ~10s, 8 keyframes; normalized coords, basket toward +x. */
const T8 = [0, 1428, 2857, 4285, 5714, 7142, 8571, 10_000] as const;
const T8_TRANSITION = [0, 900, 1800, 2800, 3900, 5000, 6000, 7000] as const;

function player(id: string, team: "offense" | "defense", number: number, label = String(number)): PlayerActor {
  return { id, type: "player", team, number, label };
}

function ball(heldBy?: string): BallActor {
  return heldBy ? { id: "ball", type: "ball", heldBy } : { id: "ball", type: "ball" };
}

function kf(t: number, poses: PoseMap): Keyframe {
  return { t, poses };
}

export function localizedText(value: LocalizedText, lang: "zh" | "en") {
  return value[lang];
}

/** Clone a built-in before use so localized teaching copy never mutates the catalog. */
export function localizeTemplateDocument(
  template: Template,
  lang: "zh" | "en",
  t: (key: string) => string,
): TacticDocumentV1 {
  const document = structuredClone(template.document);
  document.meta = {
    ...document.meta,
    name: t(template.nameKey),
    description: t(template.descKey),
    templateId: template.id,
    templateVersion: template.version,
    templateSource: "builtin",
  };
  document.teams = {
    ...document.teams,
    offense: { ...document.teams.offense, label: lang === "zh" ? "进攻" : "Offense" },
    defense: { ...document.teams.defense, label: lang === "zh" ? "防守" : "Defense" },
  };

  if (lang === "zh" && document.events) {
    document.events = document.events.map((event, index) => {
      const copy = template.eventCopyZh?.[index];
      if (!copy) return event;
      const next = {
        ...event,
        ...(copy.note ? { note: copy.note } : {}),
        ...(copy.readTrigger ? { readTrigger: copy.readTrigger } : {}),
        ...(copy.playerTask ? { playerTask: copy.playerTask } : {}),
        ...(copy.commonMistake ? { commonMistake: copy.commonMistake } : {}),
        ...(copy.explanation
          ? { teaching: { ...(event.teaching ?? {}), explanation: copy.explanation } }
          : {}),
      } as (typeof document.events)[number];

      if (copy.optionLabels) {
        const options = (event as { options?: unknown }).options;
        if (Array.isArray(options)) {
          (next as { options?: unknown[] }).options = options.map((option, optionIndex) => {
            if (!option || typeof option !== "object") return option;
            const label = copy.optionLabels?.[optionIndex];
            return label ? { ...option, label } : option;
          });
        }
      }
      return next;
    });
  }
  return document;
}

export const TEMPLATES: Template[] = [
  {
    id: "high-pnr",
    version: 2,
    nameKey: "tpl.highPnr.name",
    descKey: "tpl.highPnr.desc",
    coaching: {
      phase: { zh: "半场进攻", en: "Half-court offense" },
      level: "intermediate",
      format: "5v5",
      coverage: { zh: "沉退 + 弱侧低位协防", en: "Drop + low-man tag" },
      focus: [
        { zh: "掩护角度与贴肩过掩护", en: "Screen angle and shoulder-to-hip usage" },
        { zh: "口袋传球与弱侧 lift 的二次阅读", en: "Pocket pass and weak-side lift read" },
      ],
      reads: [
        { zh: "防守沉退：持球人先压迫罚球线与篮筐", en: "Drop stays back: pressure the nail and rim first" },
        { zh: "内线收缩：口袋传给顺下 5 号", en: "Big contains the ball: hit 5 on the pocket pass" },
        { zh: "弱侧低位协防：顺下球员分到 lift 的 2 号", en: "Low man tags: roller kicks to 2 lifting behind the tag" },
      ],
      previewAtMs: 4300,
    },
    eventCopyZh: {
      0: {
        note: "5 号在防守人外侧髋部定住高位挡拆，1 号贴肩使用掩护。",
        readTrigger: "D1 挤过掩护、D5 留在罚球线以下时，进入沉退阅读。",
        playerTask: "5 号双脚站稳并保持 0.5 秒；1 号先压迫掩护再转角。",
        commonMistake: "掩护人边移动边挡，或持球人提前绕开导致防守直接穿过。",
      },
      2: {
        note: "掩护结束后 5 号沿中路顺下，始终给持球人看见双手。",
        readTrigger: "D5 横移封堵持球人，顺下线随即打开。",
      },
      3: {
        note: "弱侧 2 号随低位协防向上 lift，保持传球窗口。",
        playerTask: "2 号在防守视线转向顺下时移动，不要过早离开底角。",
      },
      4: {
        note: "转角后的第一阅读是篮筐，第二阅读是口袋传球，第三阅读是弱侧 lift。",
        optionLabels: ["抛投 / 攻筐", "口袋传 5 号", "跳传 lift 2 号"],
      },
      5: {
        note: "D5 继续沉退并封住持球路线时，1 号把球送到 5 号顺下手边。",
        readTrigger: "内线防守同时面对球与顺下，且双脚仍在限制区外。",
        commonMistake: "传球过晚，让弱侧低位协防先站到顺下路线。",
      },
      6: {
        note: "5 号接球先看篮筐；低位协防完全收缩后再分到 lift。",
        optionLabels: ["篮下终结", "分球 lift 2 号"],
      },
      7: {
        note: "弱侧低位协防收缩后，5 号分球给向上 lift 的 2 号。",
        readTrigger: "D2 的身体进入油漆区，无法同时覆盖顺下与外线。",
      },
    },
    document: {
      schemaVersion: 2,
      meta: {
        name: "High Pick-and-Roll vs Drop (5v5)",
        description:
          "High spread pick-and-roll: 5 sets the screen at the top, 1 turns the corner, the low defender tags the roll, and 5 can kick to the lifted corner.",
        category: "半场进攻",
        tags: ["spread", "pick-and-roll", "drop", "pocket", "lift"],
        court: HALF_COURT,
        durationMs: 10_000,
      },
      teams: BASE_TEAMS,
      actors: [
        player("o1", "offense", 1),
        player("o2", "offense", 2),
        player("o3", "offense", 3),
        player("o4", "offense", 4),
        player("o5", "offense", 5),
        player("d1", "defense", 1, "D1"),
        player("d2", "defense", 2, "D2"),
        player("d3", "defense", 3, "D3"),
        player("d4", "defense", 4, "D4"),
        player("d5", "defense", 5, "D5"),
        ball("o1"),
      ],
      keyframes: [
        kf(T8[0], {
          o1: { x: 0.3, y: 0.5, facingDeg: 88 },
          o2: { x: 0.86, y: 0.08, facingDeg: 205 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.56, y: 0.78, facingDeg: 130 },
          o5: { x: 0.52, y: 0.56, facingDeg: 260 },
          d1: { x: 0.35, y: 0.5, facingDeg: 268 },
          d2: { x: 0.82, y: 0.12, facingDeg: 40 },
          d3: { x: 0.82, y: 0.88, facingDeg: 320 },
          d4: { x: 0.58, y: 0.72, facingDeg: 238 },
          d5: { x: 0.57, y: 0.54, facingDeg: 268 },
        }),
        kf(T8[1], {
          o1: { x: 0.36, y: 0.5, facingDeg: 82 },
          o2: { x: 0.86, y: 0.08, facingDeg: 205 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.57, y: 0.78, facingDeg: 130 },
          o5: { x: 0.44, y: 0.53, facingDeg: 95, cpx: 0.48, cpy: 0.56 },
          d1: { x: 0.4, y: 0.5, facingDeg: 260 },
          d2: { x: 0.82, y: 0.12, facingDeg: 40 },
          d3: { x: 0.82, y: 0.88, facingDeg: 320 },
          d4: { x: 0.59, y: 0.72, facingDeg: 240 },
          d5: { x: 0.56, y: 0.52, facingDeg: 268 },
        }),
        kf(T8[2], {
          o1: { x: 0.46, y: 0.57, facingDeg: 70 },
          o2: { x: 0.86, y: 0.08, facingDeg: 205 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.58, y: 0.78, facingDeg: 130 },
          o5: { x: 0.45, y: 0.53, facingDeg: 88 },
          d1: { x: 0.47, y: 0.57, facingDeg: 248 },
          d2: { x: 0.82, y: 0.12, facingDeg: 40 },
          d3: { x: 0.82, y: 0.88, facingDeg: 320 },
          d4: { x: 0.6, y: 0.72, facingDeg: 240 },
          d5: { x: 0.58, y: 0.51, facingDeg: 265 },
        }),
        kf(T8[3], {
          o1: { x: 0.58, y: 0.62, facingDeg: 55, cpx: 0.52, cpy: 0.62 },
          o2: { x: 0.84, y: 0.1, facingDeg: 205 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.6, y: 0.78, facingDeg: 135 },
          o5: { x: 0.57, y: 0.53, facingDeg: 70 },
          d1: { x: 0.53, y: 0.58, facingDeg: 235, cpx: 0.48, cpy: 0.56 },
          d2: { x: 0.8, y: 0.16, facingDeg: 46 },
          d3: { x: 0.82, y: 0.88, facingDeg: 320 },
          d4: { x: 0.66, y: 0.69, facingDeg: 245 },
          d5: { x: 0.63, y: 0.51, facingDeg: 260 },
        }),
        kf(T8[4], {
          o1: { x: 0.69, y: 0.6, facingDeg: 35 },
          o2: { x: 0.8, y: 0.16, facingDeg: 205 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.62, y: 0.78, facingDeg: 140 },
          o5: { x: 0.69, y: 0.52, facingDeg: 55 },
          d1: { x: 0.61, y: 0.57, facingDeg: 232 },
          d2: { x: 0.75, y: 0.33, facingDeg: 60 },
          d3: { x: 0.82, y: 0.88, facingDeg: 320 },
          d4: { x: 0.73, y: 0.58, facingDeg: 258 },
          d5: { x: 0.72, y: 0.5, facingDeg: 260 },
        }),
        kf(T8[5], {
          o1: { x: 0.78, y: 0.57, facingDeg: 28 },
          o2: { x: 0.78, y: 0.23, facingDeg: 198 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.66, y: 0.77, facingDeg: 145 },
          o5: { x: 0.8, y: 0.51, facingDeg: 35 },
          d1: { x: 0.69, y: 0.55, facingDeg: 225 },
          d2: { x: 0.76, y: 0.4, facingDeg: 70 },
          d3: { x: 0.82, y: 0.88, facingDeg: 310 },
          d4: { x: 0.7, y: 0.72, facingDeg: 262 },
          d5: { x: 0.78, y: 0.47, facingDeg: 265 },
        }),
        kf(T8[6], {
          o1: { x: 0.83, y: 0.62, facingDeg: 160 },
          o2: { x: 0.82, y: 0.23, facingDeg: 198 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.68, y: 0.77, facingDeg: 145 },
          o5: { x: 0.86, y: 0.5, facingDeg: 20 },
          d1: { x: 0.73, y: 0.57, facingDeg: 220 },
          d2: { x: 0.79, y: 0.38, facingDeg: 78 },
          d3: { x: 0.82, y: 0.88, facingDeg: 305 },
          d4: { x: 0.72, y: 0.7, facingDeg: 268 },
          d5: { x: 0.83, y: 0.47, facingDeg: 270 },
        }),
        kf(T8[7], {
          o1: { x: 0.82, y: 0.64, facingDeg: 160 },
          o2: { x: 0.86, y: 0.16, facingDeg: 205 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.69, y: 0.77, facingDeg: 145 },
          o5: { x: 0.86, y: 0.5, facingDeg: 30 },
          d1: { x: 0.74, y: 0.58, facingDeg: 220 },
          d2: { x: 0.83, y: 0.2, facingDeg: 80 },
          d3: { x: 0.82, y: 0.88, facingDeg: 305 },
          d4: { x: 0.74, y: 0.68, facingDeg: 260 },
          d5: { x: 0.83, y: 0.47, facingDeg: 270 },
        }),
      ],
      events: [
        {
          t: 2350,
          kind: "screen",
          from: "o5",
          to: "o1",
          angle: 90,
          screenSubtype: "ball",
          coverage: "drop",
          note: "5 gets stationary on the defender's outside hip; 1 uses the screen shoulder-to-hip.",
          teaching: { concept: "screen" },
          readTrigger: "D1 trails over while D5 stays below the level of the screen.",
          playerTask: "5 holds a legal base for half a second; 1 pressures the screen before turning the corner.",
          commonMistake: "A moving screen or a wide route lets the on-ball defender recover through the gap.",
        },
        { t: 2950, kind: "screen_end", from: "o5" },
        {
          t: 3300,
          kind: "cut",
          from: "o5",
          cut: "basket",
          note: "5 rolls down the middle with both hands visible after releasing the screen.",
          teaching: { concept: "cut" },
          readTrigger: "D5 slides across to contain the ball and opens the roll lane.",
        },
        {
          t: 4800,
          kind: "cut",
          from: "o2",
          cut: "lift",
          note: "2 lifts behind the low-man tag to preserve the weak-side passing window.",
          teaching: { concept: "spacing" },
          playerTask: "Move only after the defender turns attention to the roller.",
        },
        {
          t: 5600,
          kind: "finish_options",
          from: "o1",
          durationMs: 1300,
          note: "Read rim first, pocket second, and the weak-side lift third.",
          teaching: { concept: "finish" },
          options: [
            { kind: "shot", label: "Floater / rim", x: 0.8875, y: 0.5, priority: "primary" },
            { kind: "pass", label: "Pocket 5", to: "o5", priority: "counter" },
            { kind: "pass", label: "Lift 2", to: "o2", priority: "safety" },
          ],
        },
        {
          t: 7200,
          kind: "pass",
          from: "o1",
          to: "o5",
          note: "1 delivers the pocket pass once D5 commits to the drive.",
          teaching: { concept: "pass" },
          readTrigger: "The drop defender faces the ball and the roller at the same time.",
          commonMistake: "Passing late allows the low man to occupy the rolling lane first.",
        },
        {
          t: 7600,
          kind: "finish_options",
          from: "o5",
          durationMs: 1200,
          note: "5 finishes if the lane stays open and kicks out only after the tag fully commits.",
          teaching: { concept: "finish" },
          options: [
            { kind: "shot", label: "Rim finish", x: 0.8875, y: 0.5, priority: "primary" },
            { kind: "pass", label: "Lift 2", to: "o2", priority: "counter" },
          ],
        },
        {
          t: 8850,
          kind: "pass",
          from: "o5",
          to: "o2",
          note: "5 kicks to 2 lifting behind the low-man tag.",
          teaching: { concept: "pass" },
          readTrigger: "D2 has both feet in the paint and cannot cover the roll and the perimeter.",
        },
      ],
      ...COMMON_DOC,
    },
  },
  {
    id: "fast-break",
    version: 2,
    nameKey: "tpl.fastBreak.name",
    descKey: "tpl.fastBreak.desc",
    coaching: {
      phase: { zh: "快攻转换", en: "Transition" },
      level: "foundation",
      format: "3v2",
      coverage: { zh: "I 字退防", en: "I-formation defense" },
      focus: [
        { zh: "中路持球、双翼拉宽到边线跑道", en: "Middle push with both wings in wide lanes" },
        { zh: "吸引一名防守后完成额外传球", en: "Commit one defender and make the extra pass" },
      ],
      reads: [
        { zh: "顶防后退：中路直接攻筐", en: "Top defender backpedals: attack the rim" },
        { zh: "顶防停球：传给外侧跑道", en: "Top defender stops ball: pitch to the wing" },
        { zh: "底防扑球：翼侧再做一次 extra pass", en: "Back defender closes out: make the extra pass" },
      ],
      previewAtMs: 4300,
    },
    eventCopyZh: {
      0: {
        note: "两翼跑满宽度，中路持球人持续攻击，直到顶防明确停球。",
        readTrigger: "顶防仍在后退时继续攻筐；顶防双脚站定后立即 pitch。",
        playerTask: "持球人不能过早横传，两翼保持在边线跑道外侧。",
        commonMistake: "中路持球人横向运球，把两名防守重新带到同一条传球线上。",
      },
      1: {
        note: "中路吸引顶防后传给宽侧跑道，让底防必须在篮筐与球之间做选择。",
        readTrigger: "D1 停球、D2 仍守在篮筐正面。",
      },
      2: {
        note: "底防扑向接球翼侧时，立即 extra pass 给另一侧完成终结。",
        readTrigger: "D2 离开篮筐线并把胸口转向 2 号。",
        commonMistake: "2 号停球观察太久，给底防争取到二次轮转时间。",
      },
      3: {
        note: "额外传球后的第一选择是篮下终结；只有追防封住篮板前方才停球。",
        optionLabels: ["篮下终结"],
      },
    },
    document: {
      schemaVersion: 2,
      meta: {
        name: "Primary Break 3v2",
        description:
          "Classic 3-on-2 break: ball stays in the middle, wings run wide lanes, the top defender stops the ball, then the wing makes the extra pass when the back defender rotates.",
        category: "快攻转换",
        tags: ["transition", "3v2", "draw-and-pitch", "extra-pass"],
        tempo: "walkthrough",
        court: FULL_COURT,
        durationMs: 7000,
      },
      teams: BASE_TEAMS,
      actors: [
        player("o1", "offense", 1),
        player("o2", "offense", 2),
        player("o3", "offense", 3),
        player("d1", "defense", 1, "D1"),
        player("d2", "defense", 2, "D2"),
        ball("o1"),
      ],
      keyframes: [
        kf(T8_TRANSITION[0], {
          o1: { x: 0.08, y: 0.5, facingDeg: 88 },
          o2: { x: 0.06, y: 0.88, facingDeg: 84 },
          o3: { x: 0.06, y: 0.12, facingDeg: 96 },
          d1: { x: 0.68, y: 0.52, facingDeg: 268 },
          d2: { x: 0.84, y: 0.5, facingDeg: 268 },
        }),
        kf(T8_TRANSITION[1], {
          o1: { x: 0.2, y: 0.5, facingDeg: 88 },
          o2: { x: 0.19, y: 0.88, facingDeg: 82 },
          o3: { x: 0.19, y: 0.12, facingDeg: 98 },
          d1: { x: 0.67, y: 0.52, facingDeg: 268 },
          d2: { x: 0.84, y: 0.5, facingDeg: 268 },
        }),
        kf(T8_TRANSITION[2], {
          o1: { x: 0.34, y: 0.5, facingDeg: 88 },
          o2: { x: 0.33, y: 0.87, facingDeg: 78 },
          o3: { x: 0.33, y: 0.13, facingDeg: 102 },
          d1: { x: 0.66, y: 0.52, facingDeg: 268 },
          d2: { x: 0.84, y: 0.5, facingDeg: 268 },
        }),
        kf(T8_TRANSITION[3], {
          o1: { x: 0.5, y: 0.5, facingDeg: 88 },
          o2: { x: 0.5, y: 0.86, facingDeg: 76 },
          o3: { x: 0.5, y: 0.14, facingDeg: 104 },
          d1: { x: 0.66, y: 0.52, facingDeg: 270 },
          d2: { x: 0.84, y: 0.5, facingDeg: 270 },
        }),
        kf(T8_TRANSITION[4], {
          o1: { x: 0.62, y: 0.5, facingDeg: 80 },
          o2: { x: 0.65, y: 0.83, facingDeg: 68 },
          o3: { x: 0.64, y: 0.17, facingDeg: 112 },
          d1: { x: 0.67, y: 0.52, facingDeg: 276 },
          d2: { x: 0.84, y: 0.5, facingDeg: 270 },
        }),
        kf(T8_TRANSITION[5], {
          o1: { x: 0.71, y: 0.51, facingDeg: 45 },
          o2: { x: 0.78, y: 0.78, facingDeg: 60 },
          o3: { x: 0.76, y: 0.24, facingDeg: 100, cpx: 0.72, cpy: 0.2 },
          d1: { x: 0.72, y: 0.54, facingDeg: 285 },
          d2: { x: 0.85, y: 0.58, facingDeg: 292 },
        }),
        kf(T8_TRANSITION[6], {
          o1: { x: 0.74, y: 0.52, facingDeg: 40 },
          o2: { x: 0.86, y: 0.73, facingDeg: 35 },
          o3: { x: 0.86, y: 0.36, facingDeg: 62, cpx: 0.82, cpy: 0.28 },
          d1: { x: 0.76, y: 0.54, facingDeg: 282 },
          d2: { x: 0.88, y: 0.62, facingDeg: 300 },
        }),
        kf(T8_TRANSITION[7], {
          o1: { x: 0.76, y: 0.52, facingDeg: 38 },
          o2: { x: 0.88, y: 0.7, facingDeg: 35 },
          o3: { x: 0.8875, y: 0.5, facingDeg: 35 },
          d1: { x: 0.79, y: 0.54, facingDeg: 282 },
          d2: { x: 0.9, y: 0.56, facingDeg: 285 },
        }),
      ],
      events: [
        {
          t: 2700,
          kind: "teaching",
          note: "Both wings sprint wide while the middle handler attacks until the top defender declares a stop.",
          teaching: { concept: "spacing" },
          readTrigger: "Keep attacking while the top defender backpedals; pitch when that defender plants to stop the ball.",
          playerTask: "The handler stays north-south and both wings remain outside their lane lines.",
          commonMistake: "An early lateral pass lets both defenders guard the same line again.",
        },
        {
          t: 4500,
          kind: "pass",
          from: "o1",
          to: "o2",
          note: "The middle handler commits the top defender and pitches to the wide lane.",
          teaching: { concept: "pass" },
          readTrigger: "D1 stops the ball while D2 remains between the rim and both wings.",
        },
        {
          t: 5900,
          kind: "pass",
          from: "o2",
          to: "o3",
          note: "The wing makes the extra pass as the back defender leaves the rim line.",
          teaching: { concept: "pass" },
          readTrigger: "D2 turns chest and momentum toward 2, leaving 3 behind the rotation.",
          commonMistake: "Holding the catch gives the back defender time for a second rotation.",
        },
        {
          t: 6400,
          kind: "finish_options",
          from: "o3",
          durationMs: 600,
          note: "Finish at the rim before the recovering top defender can contest from behind.",
          teaching: { concept: "finish" },
          options: [
            { kind: "shot", label: "Rim finish", x: 0.8875, y: 0.5, priority: "primary" },
          ],
        },
      ],
      ...COMMON_DOC,
    },
  },
  {
    id: "horns",
    version: 2,
    nameKey: "tpl.horns.name",
    descKey: "tpl.horns.desc",
    coaching: {
      phase: { zh: "半场进攻", en: "Half-court offense" },
      level: "advanced",
      format: "5v5",
      coverage: { zh: "换防", en: "Switch" },
      focus: [
        { zh: "肘区进球后的 flare 角度", en: "Flare angle after the elbow entry" },
        { zh: "换防后先看 slip，再看外弹射手", en: "Read the slip before the flaring shooter" },
      ],
      reads: [
        { zh: "两名防守沟通迟缓：5 号立即 slip", en: "Late switch communication: 5 slips immediately" },
        { zh: "防守收缩 slip：4 号传给外弹的 2 号", en: "Defense sinks to the slip: 4 hits 2 on the flare" },
        { zh: "换防大个贴外弹：2 号喂给 5 号 slip", en: "Switched big stays with the flare: 2 feeds 5 on the slip" },
      ],
      previewAtMs: 5200,
    },
    eventCopyZh: {
      0: {
        note: "1 号把球送入强侧肘区 4 号，并清空到强侧翼。",
        playerTask: "4 号接球后先转身看篮筐，再把视线移到弱侧 flare。",
      },
      1: {
        note: "5 号在弱侧给 2 号设置 flare 掩护，迫使防守换防。",
        readTrigger: "D2 与 D5 交换对位后，5 号立即获得 slip 路线。",
        playerTask: "5 号短暂停稳；2 号先贴肩再向外线拉开。",
        commonMistake: "2 号向油漆区卷切，会把换防两人和持球点挤在同一区域。",
      },
      2: {
        note: "2 号借 flare 掩护退到弱侧外线，保持与 5 号 slip 的双重威胁。",
      },
      4: {
        note: "换防后的弱侧防守收缩 slip 时，4 号把球传给外弹的 2 号。",
        readTrigger: "D5 的站位低于 2 号传球线并优先保护篮下。",
      },
      5: {
        note: "D5 继续贴住射手时，2 号立即击地传给换防错位后的 5 号 slip。",
        readTrigger: "D2 留在 5 号身后，篮筐前没有第二名护筐者。",
      },
    },
    document: {
      schemaVersion: 2,
      meta: {
        name: "Horns Flare vs Switch (5v5)",
        description:
          "Horns entry into a flare screen: 1 enters to the elbow and clears, the weak big flares the shooter out, then slips if the defense switches too high.",
        category: "半场进攻",
        tags: ["horns", "flare", "switch", "slip"],
        court: HALF_COURT,
        durationMs: 10_000,
      },
      teams: BASE_TEAMS,
      actors: [
        player("o1", "offense", 1),
        player("o2", "offense", 2),
        player("o3", "offense", 3),
        player("o4", "offense", 4),
        player("o5", "offense", 5),
        player("d1", "defense", 1, "D1"),
        player("d2", "defense", 2, "D2"),
        player("d3", "defense", 3, "D3"),
        player("d4", "defense", 4, "D4"),
        player("d5", "defense", 5, "D5"),
        ball("o1"),
      ],
      keyframes: [
        kf(T8[0], {
          o1: { x: 0.3, y: 0.5, facingDeg: 88 },
          o2: { x: 0.86, y: 0.08, facingDeg: 205 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.56, y: 0.64, facingDeg: 92 },
          o5: { x: 0.56, y: 0.36, facingDeg: 88 },
          d1: { x: 0.35, y: 0.5, facingDeg: 268 },
          d2: { x: 0.82, y: 0.12, facingDeg: 40 },
          d3: { x: 0.82, y: 0.88, facingDeg: 320 },
          d4: { x: 0.6, y: 0.64, facingDeg: 270 },
          d5: { x: 0.6, y: 0.36, facingDeg: 270 },
        }),
        kf(T8[1], {
          o1: { x: 0.38, y: 0.54, facingDeg: 70 },
          o2: { x: 0.86, y: 0.08, facingDeg: 205 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.58, y: 0.64, facingDeg: 92 },
          o5: { x: 0.56, y: 0.36, facingDeg: 88 },
          d1: { x: 0.42, y: 0.54, facingDeg: 255 },
          d2: { x: 0.82, y: 0.12, facingDeg: 40 },
          d3: { x: 0.82, y: 0.88, facingDeg: 320 },
          d4: { x: 0.61, y: 0.64, facingDeg: 270 },
          d5: { x: 0.6, y: 0.36, facingDeg: 270 },
        }),
        kf(T8[2], {
          o1: { x: 0.5, y: 0.62, facingDeg: 35, cpx: 0.44, cpy: 0.52 },
          o2: { x: 0.82, y: 0.1, facingDeg: 205 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.6, y: 0.64, facingDeg: 55 },
          o5: { x: 0.57, y: 0.36, facingDeg: 88 },
          d1: { x: 0.5, y: 0.58, facingDeg: 140, cpx: 0.44, cpy: 0.52 },
          d2: { x: 0.79, y: 0.14, facingDeg: 45 },
          d3: { x: 0.82, y: 0.88, facingDeg: 320 },
          d4: { x: 0.63, y: 0.63, facingDeg: 250 },
          d5: { x: 0.61, y: 0.36, facingDeg: 270 },
        }),
        kf(T8[3], {
          o1: { x: 0.62, y: 0.78, facingDeg: 155, cpx: 0.56, cpy: 0.72 },
          o2: { x: 0.72, y: 0.2, facingDeg: 198 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.6, y: 0.63, facingDeg: 45 },
          o5: { x: 0.68, y: 0.25, facingDeg: 95 },
          d1: { x: 0.62, y: 0.74, facingDeg: 335 },
          d2: { x: 0.74, y: 0.23, facingDeg: 55 },
          d3: { x: 0.82, y: 0.88, facingDeg: 320 },
          d4: { x: 0.64, y: 0.61, facingDeg: 245 },
          d5: { x: 0.65, y: 0.35, facingDeg: 255 },
        }),
        kf(T8[4], {
          o1: { x: 0.72, y: 0.82, facingDeg: 165 },
          o2: { x: 0.64, y: 0.24, facingDeg: 120, cpx: 0.68, cpy: 0.2 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.6, y: 0.62, facingDeg: 40 },
          o5: { x: 0.68, y: 0.25, facingDeg: 90 },
          d1: { x: 0.71, y: 0.78, facingDeg: 345 },
          d2: { x: 0.66, y: 0.36, facingDeg: 72, cpx: 0.72, cpy: 0.25 },
          d3: { x: 0.82, y: 0.88, facingDeg: 315 },
          d4: { x: 0.65, y: 0.59, facingDeg: 240 },
          d5: { x: 0.62, y: 0.24, facingDeg: 255 },
        }),
        kf(T8[5], {
          o1: { x: 0.72, y: 0.84, facingDeg: 165 },
          o2: { x: 0.56, y: 0.18, facingDeg: 65 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.61, y: 0.6, facingDeg: 35 },
          o5: { x: 0.75, y: 0.42, facingDeg: 70 },
          d1: { x: 0.7, y: 0.8, facingDeg: 345 },
          d2: { x: 0.72, y: 0.4, facingDeg: 235 },
          d3: { x: 0.82, y: 0.88, facingDeg: 315 },
          d4: { x: 0.66, y: 0.56, facingDeg: 235 },
          d5: { x: 0.63, y: 0.25, facingDeg: 255 },
        }),
        kf(T8[6], {
          o1: { x: 0.72, y: 0.84, facingDeg: 165 },
          o2: { x: 0.52, y: 0.14, facingDeg: 50 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.63, y: 0.56, facingDeg: 30 },
          o5: { x: 0.8, y: 0.44, facingDeg: 40 },
          d1: { x: 0.7, y: 0.8, facingDeg: 345 },
          d2: { x: 0.79, y: 0.47, facingDeg: 230 },
          d3: { x: 0.82, y: 0.88, facingDeg: 315 },
          d4: { x: 0.68, y: 0.52, facingDeg: 235 },
          d5: { x: 0.54, y: 0.17, facingDeg: 260 },
        }),
        kf(T8[7], {
          o1: { x: 0.72, y: 0.84, facingDeg: 165 },
          o2: { x: 0.52, y: 0.12, facingDeg: 45 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.64, y: 0.52, facingDeg: 25 },
          o5: { x: 0.86, y: 0.48, facingDeg: 35 },
          d1: { x: 0.7, y: 0.8, facingDeg: 345 },
          d2: { x: 0.83, y: 0.48, facingDeg: 230 },
          d3: { x: 0.82, y: 0.88, facingDeg: 310 },
          d4: { x: 0.7, y: 0.5, facingDeg: 235 },
          d5: { x: 0.54, y: 0.14, facingDeg: 265 },
        }),
      ],
      events: [
        {
          t: 2850,
          kind: "pass",
          from: "o1",
          to: "o4",
          note: "1 enters to 4 at the strong elbow and clears to the strong wing.",
          teaching: { concept: "pass" },
          playerTask: "4 squares to the rim before turning attention to the weak-side flare.",
        },
        {
          t: 4450,
          kind: "screen",
          from: "o5",
          to: "o2",
          angle: -35,
          screenSubtype: "flare",
          coverage: "switch",
          note: "5 gets stationary for 2's flare and forces D2/D5 to switch.",
          teaching: { concept: "screen" },
          readTrigger: "Once D2 and D5 exchange assignments, 5 owns the inside slip lane.",
          playerTask: "5 holds briefly; 2 runs shoulder-to-hip before widening outside the arc.",
          commonMistake: "Curling into the paint crowds the switch, the elbow, and the passing lane.",
        },
        {
          t: 4550,
          kind: "cut",
          from: "o2",
          cut: "flare",
          note: "2 flares to the weak-side perimeter while 5 threatens the slip.",
          teaching: { concept: "cut" },
        },
        { t: 5050, kind: "screen_end", from: "o5" },
        {
          t: 6500,
          kind: "pass",
          from: "o4",
          to: "o2",
          note: "4 hits 2 on the flare after the switched big sinks toward the slip.",
          teaching: { concept: "pass" },
          readTrigger: "D5 sits below 2's passing line to protect the rim.",
        },
        {
          t: 8800,
          kind: "pass",
          from: "o2",
          to: "o5",
          note: "2 feeds 5 slipping inside when the switched big stays attached to the shooter.",
          teaching: { concept: "pass" },
          readTrigger: "D2 trails 5 and no second rim protector occupies the lane.",
        },
      ],
      ...COMMON_DOC,
    },
  },
  {
    id: "handoff",
    version: 2,
    nameKey: "tpl.handoff.name",
    descKey: "tpl.handoff.desc",
    coaching: {
      phase: { zh: "半场进攻", en: "Half-court offense" },
      level: "intermediate",
      format: "5v5",
      coverage: { zh: "追防 + 内线回收", en: "Chase/over + big contain" },
      focus: [
        { zh: "下掩护与手递手的衔接时机", en: "Timing the pin-down into the handoff" },
        { zh: "接球人贴肩转角，递手人短顺下", en: "Receiver turns shoulder-to-hip; giver short-rolls" },
      ],
      reads: [
        { zh: "追防落后：2 号转角攻筐", en: "Chaser trails: 2 turns the corner" },
        { zh: "内线协防持球：回传 5 号短顺下", en: "Big contains: hit 5 on the short roll" },
        { zh: "弱侧低位 tag：分给 lift 的 3 号", en: "Low man tags: kick to 3 lifting weak side" },
      ],
      previewAtMs: 5900,
    },
    eventCopyZh: {
      0: {
        note: "4 号给 2 号做下掩护，2 号贴肩卷出进入手递手路线。",
        playerTask: "4 号提前站稳；2 号先压低防守人再改变速度。",
        commonMistake: "掩护人移动或 2 号绕大弧线，都会让追防者轻松穿过。",
      },
      1: { note: "1 号把球传给肘区 5 号后清空，为 Chicago 动作让出中路。" },
      3: { note: "2 号从下掩护贴肩卷出，双手准备接手递手。" },
      4: {
        note: "5 号与 2 号完成真正的手递手；2 号接球后直接转角。",
        readTrigger: "D2 从身后追防、D5 留在手递手下方时，2 号保持向篮筐压力。",
        playerTask: "递球点在 2 号外侧手；两人肩膀间不留防守穿过的空隙。",
      },
      5: { note: "手递手完成后 5 号短暂挡住追防，再进入短顺下。" },
      7: {
        note: "转角后依次阅读篮筐、5 号短顺下和弱侧 lift。",
        optionLabels: ["攻筐", "回传 5 号短顺下", "分球 lift 3 号"],
      },
      8: {
        note: "弱侧低位协防 tag 5 号后，2 号分给向上 lift 的 3 号。",
        readTrigger: "D3 收进油漆区，且回位路线被顺下球员挡住。",
      },
    },
    document: {
      schemaVersion: 2,
      meta: {
        name: "Chicago DHO vs Chase (5v5)",
        description:
          "Pin-down into dribble handoff: 1 enters to 5, 4 pins down for 2, 2 catches the handoff going downhill, and the weak corner lifts as the help tags.",
        category: "半场进攻",
        tags: ["chicago", "pin-down", "handoff", "short-roll"],
        court: HALF_COURT,
        durationMs: 10_000,
      },
      teams: BASE_TEAMS,
      actors: [
        player("o1", "offense", 1),
        player("o2", "offense", 2),
        player("o3", "offense", 3),
        player("o4", "offense", 4),
        player("o5", "offense", 5),
        player("d1", "defense", 1, "D1"),
        player("d2", "defense", 2, "D2"),
        player("d3", "defense", 3, "D3"),
        player("d4", "defense", 4, "D4"),
        player("d5", "defense", 5, "D5"),
        ball("o1"),
      ],
      keyframes: [
        kf(T8[0], {
          o1: { x: 0.3, y: 0.52, facingDeg: 86 },
          o2: { x: 0.9, y: 0.16, facingDeg: 205 },
          o3: { x: 0.9, y: 0.84, facingDeg: 155 },
          o4: { x: 0.81, y: 0.245, facingDeg: 150 },
          o5: { x: 0.58, y: 0.5, facingDeg: 90 },
          d1: { x: 0.35, y: 0.52, facingDeg: 266 },
          d2: { x: 0.84, y: 0.2, facingDeg: 45 },
          d3: { x: 0.84, y: 0.8, facingDeg: 315 },
          d4: { x: 0.76, y: 0.31, facingDeg: 330 },
          d5: { x: 0.62, y: 0.5, facingDeg: 268 },
        }),
        kf(T8[1], {
          o1: { x: 0.4, y: 0.52, facingDeg: 82 },
          o2: { x: 0.88, y: 0.17, facingDeg: 205 },
          o3: { x: 0.9, y: 0.84, facingDeg: 155 },
          o4: { x: 0.81, y: 0.245, facingDeg: 150 },
          o5: { x: 0.58, y: 0.5, facingDeg: 88 },
          d1: { x: 0.45, y: 0.52, facingDeg: 260 },
          d2: { x: 0.84, y: 0.2, facingDeg: 45 },
          d3: { x: 0.84, y: 0.8, facingDeg: 315 },
          d4: { x: 0.76, y: 0.31, facingDeg: 330 },
          d5: { x: 0.62, y: 0.5, facingDeg: 268 },
        }),
        kf(T8[2], {
          o1: { x: 0.56, y: 0.66, facingDeg: 155, cpx: 0.5, cpy: 0.58 },
          o2: { x: 0.8, y: 0.22, facingDeg: 190, cpx: 0.86, cpy: 0.18 },
          o3: { x: 0.9, y: 0.84, facingDeg: 155 },
          o4: { x: 0.81, y: 0.245, facingDeg: 160 },
          o5: { x: 0.6, y: 0.49, facingDeg: 78 },
          d1: { x: 0.53, y: 0.61, facingDeg: 235 },
          d2: { x: 0.82, y: 0.18, facingDeg: 55, cpx: 0.85, cpy: 0.19 },
          d3: { x: 0.84, y: 0.8, facingDeg: 315 },
          d4: { x: 0.75, y: 0.33, facingDeg: 330 },
          d5: { x: 0.63, y: 0.49, facingDeg: 260 },
        }),
        kf(T8[3], {
          o1: { x: 0.76, y: 0.8, facingDeg: 165 },
          o2: { x: 0.68, y: 0.34, facingDeg: 145, cpx: 0.73, cpy: 0.25 },
          o3: { x: 0.9, y: 0.84, facingDeg: 155 },
          o4: { x: 0.86, y: 0.18, facingDeg: 205 },
          o5: { x: 0.61, y: 0.47, facingDeg: 74 },
          d1: { x: 0.72, y: 0.73, facingDeg: 220 },
          d2: { x: 0.71, y: 0.31, facingDeg: 75, cpx: 0.77, cpy: 0.24 },
          d3: { x: 0.84, y: 0.79, facingDeg: 315 },
          d4: { x: 0.84, y: 0.22, facingDeg: 340 },
          d5: { x: 0.64, y: 0.46, facingDeg: 255 },
        }),
        kf(T8[4], {
          o1: { x: 0.72, y: 0.82, facingDeg: 165 },
          o2: { x: 0.62, y: 0.43, facingDeg: 70, cpx: 0.64, cpy: 0.36 },
          o3: { x: 0.9, y: 0.84, facingDeg: 155 },
          o4: { x: 0.88, y: 0.18, facingDeg: 210 },
          o5: { x: 0.6, y: 0.46, facingDeg: 70 },
          d1: { x: 0.68, y: 0.76, facingDeg: 220 },
          d2: { x: 0.61, y: 0.41, facingDeg: 90 },
          d3: { x: 0.82, y: 0.77, facingDeg: 310 },
          d4: { x: 0.84, y: 0.22, facingDeg: 338 },
          d5: { x: 0.62, y: 0.45, facingDeg: 250 },
        }),
        kf(T8[5], {
          o1: { x: 0.72, y: 0.84, facingDeg: 170 },
          o2: { x: 0.72, y: 0.53, facingDeg: 45 },
          o3: { x: 0.86, y: 0.8, facingDeg: 150 },
          o4: { x: 0.88, y: 0.18, facingDeg: 210 },
          o5: { x: 0.72, y: 0.49, facingDeg: 55 },
          d1: { x: 0.7, y: 0.78, facingDeg: 220 },
          d2: { x: 0.71, y: 0.52, facingDeg: 235 },
          d3: { x: 0.79, y: 0.68, facingDeg: 305 },
          d4: { x: 0.84, y: 0.24, facingDeg: 335 },
          d5: { x: 0.7, y: 0.5, facingDeg: 252 },
        }),
        kf(T8[6], {
          o1: { x: 0.72, y: 0.84, facingDeg: 170 },
          o2: { x: 0.84, y: 0.56, facingDeg: 35 },
          o3: { x: 0.8, y: 0.74, facingDeg: 150 },
          o4: { x: 0.88, y: 0.2, facingDeg: 210 },
          o5: { x: 0.82, y: 0.5, facingDeg: 50 },
          d1: { x: 0.7, y: 0.78, facingDeg: 220 },
          d2: { x: 0.82, y: 0.55, facingDeg: 235 },
          d3: { x: 0.78, y: 0.6, facingDeg: 300 },
          d4: { x: 0.84, y: 0.26, facingDeg: 333 },
          d5: { x: 0.8, y: 0.5, facingDeg: 252 },
        }),
        kf(T8[7], {
          o1: { x: 0.72, y: 0.84, facingDeg: 170 },
          o2: { x: 0.86, y: 0.53, facingDeg: 35 },
          o3: { x: 0.9, y: 0.8, facingDeg: 155 },
          o4: { x: 0.88, y: 0.2, facingDeg: 210 },
          o5: { x: 0.82, y: 0.48, facingDeg: 55 },
          d1: { x: 0.7, y: 0.78, facingDeg: 220 },
          d2: { x: 0.84, y: 0.53, facingDeg: 235 },
          d3: { x: 0.86, y: 0.77, facingDeg: 300 },
          d4: { x: 0.84, y: 0.28, facingDeg: 330 },
          d5: { x: 0.83, y: 0.49, facingDeg: 255 },
        }),
      ],
      events: [
        {
          t: 2500,
          kind: "screen",
          from: "o4",
          to: "o2",
          angle: -20,
          screenSubtype: "pin_down",
          coverage: "over",
          note: "4 gets stationary for 2's pin-down into the handoff route.",
          teaching: { concept: "screen" },
          playerTask: "4 arrives early; 2 lowers the defender before changing speed.",
          commonMistake: "A moving screen or a wide curl gives the chaser a clean path through.",
        },
        {
          t: 2700,
          kind: "pass",
          from: "o1",
          to: "o5",
          note: "1 enters to 5 at the elbow and clears the middle for Chicago action.",
          teaching: { concept: "pass" },
        },
        { t: 3100, kind: "screen_end", from: "o4" },
        {
          t: 3300,
          kind: "cut",
          from: "o2",
          cut: "curl",
          note: "2 curls shoulder-to-hip off the pin-down with hands ready for the handoff.",
          teaching: { concept: "cut" },
        },
        {
          t: 5600,
          kind: "handoff",
          from: "o5",
          to: "o2",
          handoff: "dho",
          coverage: "over",
          note: "5 hands directly to 2, who turns the corner without exposing a flight pass.",
          teaching: { concept: "handoff" },
          readTrigger: "D2 chases from behind while D5 stays below the handoff.",
          playerTask: "Deliver to 2's outside hand and leave no gap between shoulders.",
        },
        {
          t: 5600,
          kind: "screen",
          from: "o5",
          to: "o2",
          angle: 25,
          screenSubtype: "ball",
          coverage: "over",
          note: "5 briefly seals the chaser after the exchange, then short-rolls.",
          teaching: { concept: "screen" },
        },
        { t: 5900, kind: "screen_end", from: "o5" },
        {
          t: 7350,
          kind: "finish_options",
          from: "o2",
          durationMs: 1200,
          note: "Read rim, 5 on the short roll, then 3 lifting behind the low-man tag.",
          teaching: { concept: "finish" },
          options: [
            { kind: "shot", label: "Rim", x: 0.8875, y: 0.5, priority: "primary" },
            { kind: "pass", label: "Short roll 5", to: "o5", priority: "counter" },
            { kind: "pass", label: "Lift 3", to: "o3", priority: "safety" },
          ],
        },
        {
          t: 8700,
          kind: "pass",
          from: "o2",
          to: "o3",
          note: "2 kicks to 3 lifting behind the low helper's tag on 5.",
          teaching: { concept: "pass" },
          readTrigger: "D3 has both feet in the paint and the recovery lane is screened by the roll.",
        },
      ],
      ...COMMON_DOC,
    },
  },
  {
    id: "triangle-offense",
    version: 2,
    nameKey: "tpl.triangle.name",
    descKey: "tpl.triangle.desc",
    coaching: {
      phase: { zh: "半场进攻", en: "Half-court offense" },
      level: "advanced",
      format: "5v5",
      coverage: { zh: "人盯人 + 低位协防", en: "Man defense + post help" },
      focus: [
        { zh: "强侧翼、底角、低位保持三角间距", en: "Maintain wing-corner-post triangle spacing" },
        { zh: "低位持球时读取 split cut 与外弹", en: "Post reads the split cut and pop" },
      ],
      reads: [
        { zh: "切入通道开放：低位传给 split cutter", en: "Cutting lane opens: post hits the split cutter" },
        { zh: "协防堵篮下：回传 split pop 或 nail", en: "Help closes the rim: find the split pop or nail" },
        { zh: "弱侧收缩：跳传 3 号", en: "Weak side sinks: skip to 3" },
      ],
      previewAtMs: 6000,
    },
    eventCopyZh: {
      0: { note: "翼侧传到底角，让强侧翼、底角和低位形成稳定三角。" },
      1: {
        note: "底角把球送入低位 5 号，传球后立即进入 split 配合。",
        playerTask: "5 号接球先看篮筐与夹击来源，不要低头运球。",
      },
      2: {
        note: "2 号为翼侧 1 号设置 split 掩护，并短暂停稳。",
        readTrigger: "D1 选择追防切入、D2 留在掩护外侧时，篮下通道打开。",
        commonMistake: "掩护持续移动或离低位过近，会把三名防守带到同一区域。",
      },
      3: {
        note: "1 号贴肩通过 split 掩护后切向篮筐，2 号随即外弹。",
        playerTask: "先阅读防守再决定直切、外切或换位，不要预设路线。",
      },
      5: {
        note: "低位看见切入通道后，把球传到 1 号前方的终结手。",
        readTrigger: "D1 被掩护阻断、低位协防尚未站到篮筐线。",
      },
      6: {
        note: "终结顺序：篮筐、2 号 split pop、4 号 nail、弱侧 3 号。",
        optionLabels: ["篮下终结", "2 号 split pop", "4 号 nail", "弱侧 3 号"],
      },
    },
    document: {
      schemaVersion: 2,
      meta: {
        name: "Triangle Offense Strong-Side Split (5v5)",
        description:
          "Bulls-style triangle spacing: wing, corner and low post form the strong-side triangle, the post catches, the corner screens for the wing split cut, and the finish read marks the rim plus outlet passes.",
        category: "半场进攻",
        tags: ["triangle", "post", "split-cut", "read-and-react"],
        court: HALF_COURT,
        durationMs: 10_000,
      },
      teams: BASE_TEAMS,
      actors: [
        player("o1", "offense", 1),
        player("o2", "offense", 2),
        player("o3", "offense", 3),
        player("o4", "offense", 4),
        player("o5", "offense", 5),
        player("d1", "defense", 1, "D1"),
        player("d2", "defense", 2, "D2"),
        player("d3", "defense", 3, "D3"),
        player("d4", "defense", 4, "D4"),
        player("d5", "defense", 5, "D5"),
        ball("o1"),
      ],
      keyframes: [
        kf(T8[0], {
          o1: { x: 0.48, y: 0.72, facingDeg: 55 },
          o2: { x: 0.9, y: 0.86, facingDeg: 160 },
          o3: { x: 0.34, y: 0.38, facingDeg: 82 },
          o4: { x: 0.58, y: 0.34, facingDeg: 110 },
          o5: { x: 0.78, y: 0.66, facingDeg: 205 },
          d1: { x: 0.53, y: 0.72, facingDeg: 235 },
          d2: { x: 0.84, y: 0.82, facingDeg: 330 },
          d3: { x: 0.4, y: 0.38, facingDeg: 268 },
          d4: { x: 0.6, y: 0.38, facingDeg: 255 },
          d5: { x: 0.8, y: 0.62, facingDeg: 25 },
        }),
        kf(T8[1], {
          o1: { x: 0.55, y: 0.74, facingDeg: 45 },
          o2: { x: 0.89, y: 0.85, facingDeg: 160 },
          o3: { x: 0.36, y: 0.39, facingDeg: 80 },
          o4: { x: 0.58, y: 0.35, facingDeg: 112 },
          o5: { x: 0.79, y: 0.65, facingDeg: 205 },
          d1: { x: 0.58, y: 0.74, facingDeg: 235 },
          d2: { x: 0.85, y: 0.82, facingDeg: 330 },
          d3: { x: 0.41, y: 0.39, facingDeg: 268 },
          d4: { x: 0.6, y: 0.39, facingDeg: 255 },
          d5: { x: 0.81, y: 0.62, facingDeg: 25 },
        }),
        kf(T8[2], {
          o1: { x: 0.62, y: 0.75, facingDeg: 35 },
          o2: { x: 0.87, y: 0.83, facingDeg: 195 },
          o3: { x: 0.39, y: 0.42, facingDeg: 78 },
          o4: { x: 0.59, y: 0.36, facingDeg: 112 },
          o5: { x: 0.8, y: 0.64, facingDeg: 210 },
          d1: { x: 0.64, y: 0.75, facingDeg: 230 },
          d2: { x: 0.84, y: 0.8, facingDeg: 325 },
          d3: { x: 0.43, y: 0.42, facingDeg: 265 },
          d4: { x: 0.61, y: 0.4, facingDeg: 252 },
          d5: { x: 0.82, y: 0.62, facingDeg: 25 },
        }),
        kf(T8[3], {
          o1: { x: 0.71, y: 0.77, facingDeg: 25, cpx: 0.66, cpy: 0.75 },
          o2: { x: 0.75, y: 0.82, facingDeg: 15 },
          o3: { x: 0.41, y: 0.36, facingDeg: 82 },
          o4: { x: 0.62, y: 0.42, facingDeg: 105 },
          o5: { x: 0.8, y: 0.63, facingDeg: 208 },
          d1: { x: 0.7, y: 0.78, facingDeg: 225, cpx: 0.66, cpy: 0.76 },
          d2: { x: 0.77, y: 0.8, facingDeg: 325 },
          d3: { x: 0.44, y: 0.36, facingDeg: 270 },
          d4: { x: 0.63, y: 0.43, facingDeg: 250 },
          d5: { x: 0.82, y: 0.62, facingDeg: 25 },
        }),
        kf(T8[4], {
          o1: { x: 0.84, y: 0.64, facingDeg: 345, cpx: 0.78, cpy: 0.74 },
          o2: { x: 0.75, y: 0.82, facingDeg: 40 },
          o3: { x: 0.45, y: 0.31, facingDeg: 78 },
          o4: { x: 0.65, y: 0.43, facingDeg: 100 },
          o5: { x: 0.81, y: 0.63, facingDeg: 190 },
          d1: { x: 0.79, y: 0.68, facingDeg: 220, cpx: 0.75, cpy: 0.74 },
          d2: { x: 0.72, y: 0.78, facingDeg: 225 },
          d3: { x: 0.48, y: 0.31, facingDeg: 270 },
          d4: { x: 0.66, y: 0.45, facingDeg: 250 },
          d5: { x: 0.83, y: 0.69, facingDeg: 15 },
        }),
        kf(T8[5], {
          o1: { x: 0.84, y: 0.57, facingDeg: 315 },
          o2: { x: 0.68, y: 0.84, facingDeg: 55 },
          o3: { x: 0.55, y: 0.27, facingDeg: 72 },
          o4: { x: 0.59, y: 0.5, facingDeg: 95 },
          o5: { x: 0.81, y: 0.62, facingDeg: 185 },
          d1: { x: 0.81, y: 0.61, facingDeg: 215 },
          d2: { x: 0.69, y: 0.8, facingDeg: 225 },
          d3: { x: 0.55, y: 0.31, facingDeg: 255 },
          d4: { x: 0.63, y: 0.52, facingDeg: 250 },
          d5: { x: 0.83, y: 0.68, facingDeg: 10 },
        }),
        kf(T8[6], {
          o1: { x: 0.87, y: 0.54, facingDeg: 250 },
          o2: { x: 0.66, y: 0.86, facingDeg: 60 },
          o3: { x: 0.62, y: 0.28, facingDeg: 70 },
          o4: { x: 0.586, y: 0.5, facingDeg: 92 },
          o5: { x: 0.8, y: 0.64, facingDeg: 190 },
          d1: { x: 0.84, y: 0.57, facingDeg: 210 },
          d2: { x: 0.67, y: 0.82, facingDeg: 230 },
          d3: { x: 0.58, y: 0.31, facingDeg: 250 },
          d4: { x: 0.63, y: 0.52, facingDeg: 250 },
          d5: { x: 0.86, y: 0.64, facingDeg: 12 },
        }),
        kf(T8[7], {
          o1: { x: 0.875, y: 0.53, facingDeg: 250 },
          o2: { x: 0.66, y: 0.88, facingDeg: 60 },
          o3: { x: 0.64, y: 0.28, facingDeg: 70 },
          o4: { x: 0.586, y: 0.5, facingDeg: 92 },
          o5: { x: 0.78, y: 0.66, facingDeg: 190 },
          d1: { x: 0.85, y: 0.56, facingDeg: 210 },
          d2: { x: 0.67, y: 0.84, facingDeg: 230 },
          d3: { x: 0.6, y: 0.31, facingDeg: 248 },
          d4: { x: 0.63, y: 0.52, facingDeg: 250 },
          d5: { x: 0.82, y: 0.61, facingDeg: 12 },
        }),
      ],
      events: [
        {
          t: 1600,
          kind: "pass",
          from: "o1",
          to: "o2",
          note: "The wing-to-corner pass establishes the strong-side triangle.",
          teaching: { concept: "spacing" },
        },
        {
          t: 3200,
          kind: "pass",
          from: "o2",
          to: "o5",
          note: "2 enters the low post and immediately flows into split action.",
          teaching: { concept: "pass" },
          playerTask: "5 sees the rim and the help source before putting the ball down.",
        },
        {
          t: 4300,
          kind: "screen",
          from: "o2",
          to: "o1",
          angle: -25,
          screenSubtype: "split",
          coverage: "help_recover",
          note: "2 gets stationary for 1's split cut and releases quickly into the pop.",
          teaching: { concept: "screen" },
          readTrigger: "D1 trails the cutter while D2 stays outside the screen, opening the rim lane.",
          commonMistake: "A drifting screen or tight post spacing pulls three defenders into one area.",
        },
        {
          t: 4450,
          kind: "cut",
          from: "o1",
          cut: "split",
          note: "1 cuts shoulder-to-hip off the split screen while 2 prepares to pop.",
          teaching: { concept: "cut" },
          playerTask: "Read the defender before choosing the cut, pop, or exchange route.",
        },
        { t: 5000, kind: "screen_end", from: "o2" },
        {
          t: 6200,
          kind: "pass",
          from: "o5",
          to: "o1",
          note: "5 leads the split cutter toward the rim once the lane opens.",
          teaching: { concept: "pass" },
          readTrigger: "D1 is screened and the low helper has not reached the rim line.",
        },
        {
          t: 7600,
          kind: "finish_options",
          from: "o1",
          durationMs: 1800,
          note: "Read rim first, then the split pop, the nail, and the weak-side outlet as help commits.",
          teaching: { concept: "finish" },
          options: [
            { kind: "shot", label: "Rim", x: 0.8875, y: 0.5, priority: "primary" },
            { kind: "pass", label: "Split pop 2", to: "o2", priority: "counter" },
            { kind: "pass", label: "Nail 4", to: "o4", priority: "counter" },
            { kind: "pass", label: "Weak 3", to: "o3", priority: "safety" },
          ],
        },
      ],
      ...COMMON_DOC,
    },
  },
  {
    id: "zone-131",
    version: 2,
    nameKey: "tpl.zone131.name",
    descKey: "tpl.zone131.desc",
    coaching: {
      phase: { zh: "破联防", en: "Zone offense" },
      level: "intermediate",
      format: "5v5",
      coverage: { zh: "1-3-1 联防", en: "1-3-1 zone" },
      focus: [
        { zh: "用底角与短角牵动底线游击手", en: "Stretch the baseline runner with corner and short corner" },
        { zh: "短角吸引中路后回找 nail", en: "Short corner draws the middle, then finds the nail" },
      ],
      reads: [
        { zh: "底线游击手扑底角：传短角", en: "Baseline runner takes corner: feed short corner" },
        { zh: "中路下沉短角：回传闪入 nail 的 4 号", en: "Middle drops to short corner: hit 4 flashing to the nail" },
        { zh: "翼侧收缩 nail：4 号跳传弱侧或 high-low", en: "Wing pinches the nail: 4 skips weak side or plays high-low" },
      ],
      previewAtMs: 7100,
    },
    eventCopyZh: {
      0: {
        note: "顶部传到 overload 翼侧，迫使顶防和强侧翼同时移动。",
        playerTask: "顶部传球后向弱侧平移，保留安全回传角度。",
      },
      1: {
        note: "翼侧把球送到底角，拉长底线游击手的轮转距离。",
        readTrigger: "D5 离开篮筐线并向底角加速时，短角窗口出现。",
      },
      2: {
        note: "底角在底线游击手到位前把球传到身后的短角。",
        commonMistake: "底角停球或带球，会让联防完成 trap 并堵住短角。",
      },
      3: {
        note: "中路防守下沉短角时，4 号从盲侧闪入 nail。",
        readTrigger: "D3 的肩膀转向短角，罚球线中点无人占据。",
        playerTask: "4 号在 D3 转头后再启动，接球时面向篮筐。",
      },
      4: {
        note: "短角吸引中路后回传 nail，让 4 号在联防中心接球。",
        readTrigger: "D3 低于 5 号，强侧翼又无法同时覆盖 nail。",
      },
      5: {
        note: "4 号在 nail 接球后先投，再看 high-low，最后跳传弱侧。",
        optionLabels: ["罚球线投篮", "High-low 5 号", "弱侧跳传 1 号"],
      },
    },
    document: {
      schemaVersion: 2,
      meta: {
        name: "1-3-1 Zone vs Overload (5v5)",
        description:
          "Overload spacing against a 1-3-1: the ball goes top-wing-corner-short corner-high post while the top chaser, wings, middle and baseline runner rotate in shape.",
        category: "破联防",
        tags: ["zone-offense", "1-3-1", "overload", "short-corner", "nail"],
        court: HALF_COURT,
        durationMs: 10_000,
      },
      teams: BASE_TEAMS,
      actors: [
        player("o1", "offense", 1),
        player("o2", "offense", 2),
        player("o3", "offense", 3),
        player("o4", "offense", 4),
        player("o5", "offense", 5),
        player("d1", "defense", 1, "D1"),
        player("d2", "defense", 2, "D2"),
        player("d3", "defense", 3, "D3"),
        player("d4", "defense", 4, "D4"),
        player("d5", "defense", 5, "D5"),
        ball("o1"),
      ],
      keyframes: [
        kf(T8[0], {
          o1: { x: 0.26, y: 0.5, facingDeg: 88 },
          o2: { x: 0.48, y: 0.76, facingDeg: 65 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.54, y: 0.38, facingDeg: 110 },
          o5: { x: 0.82, y: 0.66, facingDeg: 170 },
          d1: { x: 0.38, y: 0.5, facingDeg: 90 },
          d2: { x: 0.55, y: 0.28, facingDeg: 112 },
          d3: { x: 0.62, y: 0.5, facingDeg: 88 },
          d4: { x: 0.55, y: 0.72, facingDeg: 68 },
          d5: { x: 0.82, y: 0.5, facingDeg: 270 },
        }),
        kf(T8[1], {
          o1: { x: 0.34, y: 0.55, facingDeg: 72 },
          o2: { x: 0.5, y: 0.77, facingDeg: 62 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.54, y: 0.38, facingDeg: 110 },
          o5: { x: 0.82, y: 0.66, facingDeg: 170 },
          d1: { x: 0.42, y: 0.58, facingDeg: 105 },
          d2: { x: 0.55, y: 0.3, facingDeg: 112 },
          d3: { x: 0.64, y: 0.5, facingDeg: 92 },
          d4: { x: 0.57, y: 0.74, facingDeg: 70 },
          d5: { x: 0.82, y: 0.54, facingDeg: 278 },
        }),
        kf(T8[2], {
          o1: { x: 0.34, y: 0.56, facingDeg: 72 },
          o2: { x: 0.52, y: 0.78, facingDeg: 58 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.56, y: 0.4, facingDeg: 110 },
          o5: { x: 0.82, y: 0.66, facingDeg: 170 },
          d1: { x: 0.44, y: 0.65, facingDeg: 110 },
          d2: { x: 0.55, y: 0.32, facingDeg: 114 },
          d3: { x: 0.66, y: 0.54, facingDeg: 102 },
          d4: { x: 0.63, y: 0.78, facingDeg: 62 },
          d5: { x: 0.82, y: 0.62, facingDeg: 292 },
        }),
        kf(T8[3], {
          o1: { x: 0.34, y: 0.56, facingDeg: 72 },
          o2: { x: 0.54, y: 0.78, facingDeg: 55 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.58, y: 0.42, facingDeg: 112 },
          o5: { x: 0.82, y: 0.66, facingDeg: 170 },
          d1: { x: 0.44, y: 0.7, facingDeg: 115 },
          d2: { x: 0.56, y: 0.34, facingDeg: 116 },
          d3: { x: 0.66, y: 0.58, facingDeg: 110 },
          d4: { x: 0.72, y: 0.82, facingDeg: 55 },
          d5: { x: 0.86, y: 0.8, facingDeg: 315 },
        }),
        kf(T8[4], {
          o1: { x: 0.34, y: 0.55, facingDeg: 78 },
          o2: { x: 0.52, y: 0.76, facingDeg: 65 },
          o3: { x: 0.86, y: 0.92, facingDeg: 155 },
          o4: { x: 0.6, y: 0.46, facingDeg: 115 },
          o5: { x: 0.82, y: 0.68, facingDeg: 165 },
          d1: { x: 0.43, y: 0.68, facingDeg: 112 },
          d2: { x: 0.58, y: 0.35, facingDeg: 118 },
          d3: { x: 0.7, y: 0.58, facingDeg: 118 },
          d4: { x: 0.72, y: 0.8, facingDeg: 58 },
          d5: { x: 0.9, y: 0.82, facingDeg: 310 },
        }),
        kf(T8[5], {
          o1: { x: 0.34, y: 0.53, facingDeg: 82 },
          o2: { x: 0.5, y: 0.72, facingDeg: 80 },
          o3: { x: 0.86, y: 0.9, facingDeg: 160 },
          o4: { x: 0.61, y: 0.49, facingDeg: 105 },
          o5: { x: 0.82, y: 0.68, facingDeg: 160 },
          d1: { x: 0.4, y: 0.62, facingDeg: 105 },
          d2: { x: 0.6, y: 0.34, facingDeg: 118 },
          d3: { x: 0.84, y: 0.6, facingDeg: 118 },
          d4: { x: 0.68, y: 0.74, facingDeg: 70 },
          d5: { x: 0.82, y: 0.7, facingDeg: 300 },
        }),
        kf(T8[6], {
          o1: { x: 0.34, y: 0.48, facingDeg: 88 },
          o2: { x: 0.46, y: 0.68, facingDeg: 88 },
          o3: { x: 0.84, y: 0.86, facingDeg: 160 },
          o4: { x: 0.62, y: 0.5, facingDeg: 82 },
          o5: { x: 0.8, y: 0.66, facingDeg: 165 },
          d1: { x: 0.38, y: 0.56, facingDeg: 95 },
          d2: { x: 0.58, y: 0.3, facingDeg: 112 },
          d3: { x: 0.78, y: 0.57, facingDeg: 98 },
          d4: { x: 0.6, y: 0.7, facingDeg: 78 },
          d5: { x: 0.8, y: 0.62, facingDeg: 282 },
        }),
        kf(T8[7], {
          o1: { x: 0.36, y: 0.44, facingDeg: 88 },
          o2: { x: 0.46, y: 0.68, facingDeg: 88 },
          o3: { x: 0.84, y: 0.86, facingDeg: 160 },
          o4: { x: 0.62, y: 0.5, facingDeg: 82 },
          o5: { x: 0.8, y: 0.66, facingDeg: 165 },
          d1: { x: 0.38, y: 0.5, facingDeg: 88 },
          d2: { x: 0.55, y: 0.28, facingDeg: 110 },
          d3: { x: 0.68, y: 0.54, facingDeg: 88 },
          d4: { x: 0.56, y: 0.72, facingDeg: 78 },
          d5: { x: 0.8, y: 0.54, facingDeg: 270 },
        }),
      ],
      events: [
        {
          t: 1900,
          kind: "pass",
          from: "o1",
          to: "o2",
          coverage: "zone",
          note: "The top-to-overload-wing pass shifts both the chaser and the strong-side wing.",
          teaching: { concept: "pass" },
          playerTask: "1 slides weak side after the pass to preserve a safe reversal angle.",
        },
        {
          t: 4250,
          kind: "pass",
          from: "o2",
          to: "o3",
          coverage: "zone",
          note: "The wing feeds the corner and forces the baseline runner to cover maximum distance.",
          teaching: { concept: "pass" },
          readTrigger: "When D5 accelerates to the corner, the short-corner window opens behind the rotation.",
        },
        {
          t: 5700,
          kind: "pass",
          from: "o3",
          to: "o5",
          coverage: "zone",
          note: "The corner immediately finds the short corner behind the baseline runner.",
          teaching: { concept: "pass" },
          commonMistake: "Holding or dribbling in the corner lets the zone complete its trap and close the short corner.",
        },
        {
          t: 6200,
          kind: "cut",
          from: "o4",
          cut: "flash",
          coverage: "zone",
          note: "4 flashes from the middle defender's blind side as that defender drops to the short corner.",
          teaching: { concept: "cut" },
          readTrigger: "D3 turns both shoulders toward the short corner and vacates the nail.",
          playerTask: "4 waits for the head turn, flashes hard, and catches facing the rim.",
        },
        {
          t: 7350,
          kind: "pass",
          from: "o5",
          to: "o4",
          coverage: "zone",
          note: "The short corner hits 4 at the nail after drawing the middle defender down.",
          teaching: { concept: "pass" },
          readTrigger: "D3 sits below 5 and the strong-side wing cannot cover the nail at the same time.",
        },
        {
          t: 8400,
          kind: "finish_options",
          from: "o4",
          durationMs: 1500,
          note: "At the nail, 4 reads shot first, high-low second, and the weak-side skip third.",
          teaching: { concept: "finish" },
          options: [
            { kind: "shot", label: "Nail jumper", x: 0.62, y: 0.5, priority: "primary" },
            { kind: "pass", label: "High-low 5", to: "o5", priority: "counter" },
            { kind: "pass", label: "Weak skip 1", to: "o1", priority: "safety" },
          ],
        },
      ],
      ...COMMON_DOC,
    },
  },
];
